name: "First Yaml Script Dmeo Practice"
on:
  push:
    branches:
      - master
      - main

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello"
        run: echo "Hello"
