name: "By my self"
on:
  push:
    branches:
      - main 
      - master
  pull_request:
    branches:
      - master
      - test
    types:
      - opened
      - closed

jobs:
  on_push:
    
    runs-on: ubuntu-latest
    steps:
        - name: "printing on desk"
          run: echo "Push"

  on_pull:
    
    runs-on: ubuntu-latest
    steps:
      - name: "pull demo"
        run: echo "Pull"


